apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-slave
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
      - name: redis-slave
        image: my-redis:v0.0.4
        imagePullPolicy: Never
        command: ['bash', '-c']
        args:
          - IFS='-';
            read -ra HOSTNUM <<<`hostname`;
            redis-server '/usr/local/etc/redis/slave'${HOSTNUM[-1]}'.conf';
        ports:
        - containerPort: 6379
        env:
          - name: REDIS_POD_NAME
            value: redis-slave
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
        volumeMounts:
        - name: redis-conf
          mountPath: /usr/local/etc/redis
        - name: redis-data
          mountPath: /data
          subPathExpr: $(POD_NAME)
      volumes:
      - name: redis-conf
        hostPath:
          path: /hostpath/redis/conf
      - name: redis-data
        hostPath:
          path: /hostpath/redis/slave
